spring.application.name=Work Management Platform

spring.datasource.url=jdbc:postgresql://localhost:5432/wmp
spring.datasource.username=wmp_user
spring.datasource.password=wmp_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

logging.level.org.springframework.data=DEBUG
logging.level.org.hibernate.sql=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.flywaydb=DEBUG
