CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
    username VARCHAR(50) not null unique,
    name varchar(100) not null,
    email varchar(255) not null,
    password varchar(255) not null,
    role varchar(20) not null check (role IN ('ADMIN','USER')),
    created_at TIMESTAMP WITH TIME ZONE not null default now()
);

CREATE TABLE teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
    name varchar(100) not null,
    created_at TIMESTAMP WITH TIME ZONE not null DEFAULT now()
);

CREATE TABLE team_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
    team_id BIGINT not null,
    user_id BIGINT not null,
    user_role varchar(20) not null check (user_role IN ('LEAD','MEMBER')),
    CONSTRAINT fk_membership_team foreign key (team_id) REFERENCES teams(id),
    CONSTRAINT fk_membership_user foreign key (user_id) REFERENCES users(id),
    CONSTRAINT unique_team_user unique (team_id,user_id)
);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
    title varchar(200) not null,
    description TEXT,
    created_by BIGINT not null,
    assigned_team BIGINT,
    status varchar(20) not null check (status IN ('ACTIVE','COMPLETED','ARCHIVED')),
    created_at TIMESTAMP WITH TIME ZONE not null DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_owner_user FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_assigned_team FOREIGN KEY (assigned_team) REFERENCES teams(id)
);

CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
    title varchar(200) not null,
    description TEXT,
    project_id BIGINT not null,
    assigned_to BIGINT,
    created_by BIGINT not null,
    status varchar(20) not null check (status IN ('CREATED','ASSIGNED','IN_PROGRESS','COMPLETED')),
    priority varchar(50) not null DEFAULT 'MEDIUM' check (priority IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    created_at TIMESTAMP WITH TIME ZONE not null DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_tasks_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_tasks_assigned FOREIGN KEY (assigned_to) REFERENCES users(id),
    CONSTRAINT fk_tasks_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE UNIQUE INDEX one_lead_per_team ON team_memberships(team_id) WHERE user_role = 'LEAD';
CREATE INDEX idx_project_team ON projects(assigned_team);
CREATE INDEX idx_project_created_by ON projects(created_by);
CREATE INDEX idx_project_unassigned ON projects(created_at) WHERE assigned_team IS NULL;
CREATE INDEX idx_tasks_project ON tasks(project_id);
CREATE INDEX idx_tasks_assigned ON tasks(assigned_to);
CREATE INDEX idx_tasks_status ON tasks(status);
CREATE INDEX idx_tasks_assigned_status ON tasks(assigned_to, status);
CREATE INDEX idx_tasks_priority ON tasks(priority);
CREATE INDEX idx_tasks_unassigned ON tasks(created_at) WHERE assigned_to IS NULL;